/*	Create DATABASE australia
	================================================
	================================================ */

--	USE australia;

	DELETE FROM images;
	ALTER TABLE images AUTO_INCREMENT=1;

	INSERT INTO images (title, name, src, description, gallery)
	VALUES
		('Platypus', 'platypus.jpg', 'platypus.jpg', 'Originally regarded as a hoax, the Platypus is a small furry mammal which lays eggs, has an electrically sensitive bill, webbed paws, and spends much of its time in the water.¶Platypuses are nocturnal and live in secret tunnels, and clearly not anxious for your attention.', true),
		('Wombat', 'wombat.jpg', 'wombat.jpg', 'Wombats are about a metre in length, and are furry burrowing herbivorous animals, spending most of their time underground. They have pouches which face backward so that their young don’t get inconvenienced by the dirt when the mother is burrowing.¶Occasionally, you will come across a fat-arsed wombat, but it is probably a fake.', true),
		('Echidna', 'echidna.jpg', 'echidna.jpg', 'The Echidna is a small mammal with a long snout and is covered in spines. It lays eggs; after the eggs hatch the baby echidnas live in the mother’s pouch until they become too prickly for the mother’s comfort.¶When traumatised, the echidna will roll up into spiky ball, which vaguely resembles a pom pom from hell.', true),
		('Kangaroo', 'kangaroo.jpg', 'kangaroo.jpg', 'Kangaroos range in size from small to large, and there is a type kangaroo for just about every environment in Australia. They are famous for their marsupial pouch and their method of locomotion which is to jump about on their large hind feet.¶Wallabies are smaller, though their different diets indicate different teeth.¶Kangaroos are often seen laying around and scratching themselves, and are quite at home as Australians.', true),
		('Tasmanian Devil', 'tasmanian-devil.jpg', 'tasmanian-devil.jpg', 'The Tasmanian Devil is about the size of a dog. They hunt small mammals, but despite the cartoons, feed mainly on the remains of already dead animals, possibly wabbits.', true),
		('Kookaburra', 'kookaburra.jpg', 'kookaburra.jpg', 'The Kookaburra is the largest Kingfisher (bird) in the world, known best for its cackling laughter. It eats small lizards and snakes, but will occasionally attack picnickers for their lunch.¶The laughter of the kookaburra is a very popular sound track for non-Australian jungle movies. It costs a lot of money to transport the kookaburras to the jungles just to make the sound.', true),
		('Koala', 'koala.jpg', 'koala.jpg', 'The Koala is a tree-dwelling marsupial renowned for mostly sleeping and occasionally eating leaves. They rarely drink, but rely more on the moisture on the leaves. Koalas are good climbers, and can make a lot of noise.¶Koalas spend most of their time sleeping, which is why it suits Australia so well.¶The Koala is not a bear, and rarely wears a neck tie.', true),
		('Emu', 'emu.jpg', 'emu.jpg', 'The Emu is a large flightless bird, which can be up to 2 metres tall. The female lays large eggs, after which the male incubates them and looks after the young.¶Close up, they make a funny kind of knocking noise.¶You can eat emus, but they would prefer you didn’t.', true),
		('Bilby', 'bilby.jpg', 'bilby.jpg', 'The Bilby is a mammal about the size of a rabbit, with large ears and a long tail. In recent years, it has become threatened.¶The bilby has also received a lot of recent attention, especially as a replacement for the Easter Bunny. You can go to your chocolate shop and eat one, somehow ensuring its longevity.', true),
		('Possum', 'possum.jpg', 'possum.jpg', 'The possum is a tree dwelling marsupial, though it will do nicely in your roof. They eat fruit and leaves, and seem to like those in your back yard. They have a long prehensile tail which helps with its climbing activities.¶Possums really enjoy it when you go spotting for them with a strong torch in their eyes. Dame Edna also appears to have a thing for them.', true),
		('Tawny Frogmouth', 'tawny-frogmouth.jpg', 'tawny-frogmouth.jpg', 'The Tawny Frogmouth is a bird resembling an owl, though, unlike real owls, it catches prey with its beak rather than its talons. It eats mostly insects, with the occasional frog or so to relieve the boredom.¶When not actually moving about, it closely resembles part of a tree, so if you can’t see one, maybe you can.', true),
		('Lorikeet', 'lorikeet.jpg', 'lorikeet.jpg', 'The Rainbow Lorikeet is a bird of the parrot family known for its spectacular colours. It is also known for the damage it can do to fruit trees, which explains why many farmers have lost their enthusiasm for it, despite the bird’s friendliness.¶Some people try to talk with them, presumably looking for someone at their own intellectual level.', true),
		('Galah', 'galah.jpg', 'galah.jpg', 'The Galah is a bird of the Cockatoo family with pink and grey colouring. It eats mainly seeds. The only way to tell the difference between male and female is to look at their eye colour, though one imagines the galah uses other methods.¶If someone calls you a galah, and you don‘t actually have pink and grey plumage, you’d have to wonder why.', true),
		('Wedge-Tailed Eagle', 'wedge-tailed-eagle.jpg', 'wedge-tailed-eagle.jpg', 'The Wedge-tailed Eagle is one of the largest eagles in the world, with a wing span of 2.5 metres. They are excellent predators, though they will also feed on road kill, which is the human contribution to the food cycle.¶They are occasionally referred to as wedgies, though if someone offers to give you one, it is unlikely to be an eagle, though they may also offer to give you the bird.', true),
		('Frilled Necked Lizard', 'frill-necked-lizard.jpg', 'frill-necked-lizard.jpg', 'The Frilled Neck Lizard is a little under a meter in length, with a spectacular frill around its neck, contributing somewhat to its name.¶The frill is folded out to discourage predators and competitors, though drawing attention to itself is not always regarded as a good stealth strategy.', true),
		('Goanna', 'goanna.jpg', 'goanna.jpg', 'The Lace Monitor, aka Common Goanna, is a large lizard, up to 2 metres long. It is darkish in colour and eats insects and small reptiles and mammals. Its name may derive from the Iguana, which is a completely unrelated species.¶If someone wishes to play the goanna, it probably refers to a somewhat larger musical instrument, though they may have more luck with the lizard.', true),
		('Saltwater Crocodile', 'crocodile.jpg', 'crocodile.jpg', 'The Saltwater Crocodile is the world’s largest reptile averaging 4 metres, but sometimes up to 7 metres. The sex of a hatchling is determined by the temperature of the egg.¶The Crocodile is endangered, but not nearly as much as anybody trying to take a swim nearby.', true),
		('Fairy Penguin', 'fairy-penguin.jpg', 'fairy-penguin.jpg', 'The fairy penguin is a small penguin. When not doing its bit for Australian tourism, it shares its time between the south Coast of Australia and very much colder places.¶In the evening, when the penguins come back from their aquatic escapades, tourists flock from all around, which is the sort of thing birds would do, if they too were equipped with cameras.', true),
		('Lyrebird', 'lyrebird.jpg', 'lyrebird.jpg', 'The Lyrebird is a songbird standing at a little under one metre, but that includes its tail which looks rather like a lyre, which is a sort of a harp, but calling it a harp bird would be inappropriate.¶The Lyrebird a remarkable mimic, and can sound like other animals or artificial sounds. Much like a politician, or “Liar Liar” bird to its friends.', true)
	;
