DROP TABLE IF EXISTS users;
CREATE TABLE users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	email VARCHAR(60) NOT NULL UNIQUE,
	familyname VARCHAR(40) NOT NULL,
	givenname VARCHAR(40) NOT NULL,
	password VARCHAR(255) NOT NULL,
	admin BOOLEAN NOT NULL DEFAULT FALSE
);
